# Generated by Django 3.0.5 on 2020-04-26 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bicycles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('rented_at', models.DateTimeField(auto_now_add=True)),
                ('rented_ended_at', models.DateTimeField(blank=True, null=True)),
                ('bicycles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bicycles.Bicycle')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('price', models.FloatField()),
                ('payed_at', models.DateTimeField(auto_now_add=True)),
                ('rent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rents.Rent')),
            ],
        ),
    ]
