# Generated by Django 3.0.5 on 2020-05-01 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rents', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rent',
            old_name='bicycles',
            new_name='bicycle',
        ),
    ]
