# Generated by Django 3.0.5 on 2020-04-26 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bicycle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('company_id', models.CharField(max_length=255)),
                ('price', models.FloatField()),
            ],
        ),
    ]
