# Generated by Django 3.0.5 on 2020-04-26 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bicycles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bicycles',
            name='company_name',
            field=models.CharField(default='defoult', max_length=255),
            preserve_default=False,
        ),
    ]
